### ISSUE TITLE
Duplicate Contacts

### ISSUE THREAD

**Issue by mecachisenros** [christianwach/civicrm-wp-member-sync#5]
When adding a new Membership to a contact in CiviCRM, the Member-sync plugin creates a new Wordpress user, but instead of synchronizing the Wordpress user with the CiviCRM contact, it creates a duplicate contact in CiviCRM.

I've tested this with clean Wordpress and Civicrm install with the same result, it seems the issue appears since CiviCRM 4.6.3 and also happens in 4.6.4

```
Jun 24 09:17:29  [info] $Fatal Error Details = Array
(
    [callback] => Array
        (
            [0] => CRM_Core_Error
            [1] => handle
        )

    [code] => -5
    [message] => DB Error: already exists
    [mode] => 16
    [debug_info] => INSERT INTO civicrm_uf_match (domain_id , uf_id , uf_name , contact_id ) VALUES ( 1 ,  4 , 'info@test.com' ,  1 )  [nativecode=1062 ** Duplicate entry 'info@test.com-1' for key 'UI_uf_name_domain_id']
    [type] => DB_Error
    [user_info] => INSERT INTO civicrm_uf_match (domain_id , uf_id , uf_name , contact_id ) VALUES ( 1 ,  4 , 'info@test.com' ,  1 )  [nativecode=1062 ** Duplicate entry 'info@test.com-1' for key 'UI_uf_name_domain_id']
    [to_string] => [db_error: message="DB Error: already exists" code=-5 mode=callback callback=CRM_Core_Error::handle prefix="" info="INSERT INTO civicrm_uf_match (domain_id , uf_id , uf_name , contact_id ) VALUES ( 1 ,  4 , 'info@test.com' ,  1 )  [nativecode=1062 ** Duplicate entry 'info@test.com-1' for key 'UI_uf_name_domain_id']"]
)


Jun 24 09:17:29  [info] $backTrace = #0 /var/www/menas.co/public_html/dev/wp-content/plugins/civicrm/civicrm/CRM/Core/Error.php(235): CRM_Core_Error::backtrace("backTrace", TRUE)
#1 [internal function](): CRM_Core_Error::handle(Object(DB_Error))
#2 /var/www/menas.co/public_html/dev/wp-content/plugins/civicrm/civicrm/packages/PEAR.php(931): call_user_func((Array:2), Object(DB_Error))
#3 /var/www/menas.co/public_html/dev/wp-content/plugins/civicrm/civicrm/packages/DB.php(976): PEAR_Error->PEAR_Error("DB Error: already exists", -5, 16, (Array:2), "INSERT INTO civicrm_uf_match (domain_id , uf_id , uf_name , contact_id ) VALU...")
#4 /var/www/menas.co/public_html/dev/wp-content/plugins/civicrm/civicrm/packages/PEAR.php(564): DB_Error->DB_Error(-5, 16, (Array:2), "INSERT INTO civicrm_uf_match (domain_id , uf_id , uf_name , contact_id ) VALU...")
#5 /var/www/menas.co/public_html/dev/wp-content/plugins/civicrm/civicrm/packages/DB/common.php(1905): PEAR->raiseError(NULL, -5, NULL, NULL, "INSERT INTO civicrm_uf_match (domain_id , uf_id , uf_name , contact_id ) VALU...", "DB_Error", TRUE)
#6 /var/www/menas.co/public_html/dev/wp-content/plugins/civicrm/civicrm/packages/DB/mysql.php(899): DB_common->raiseError(-5, NULL, NULL, NULL, "1062 ** Duplicate entry 'info@test.com-1' for key 'UI_uf_name_domain_id'")
#7 /var/www/menas.co/public_html/dev/wp-content/plugins/civicrm/civicrm/packages/DB/mysql.php(328): DB_mysql->mysqlRaiseError()
#8 /var/www/menas.co/public_html/dev/wp-content/plugins/civicrm/civicrm/packages/DB/common.php(1216): DB_mysql->simpleQuery("INSERT INTO civicrm_uf_match (domain_id , uf_id , uf_name , contact_id ) VALU...")
#9 /var/www/menas.co/public_html/dev/wp-content/plugins/civicrm/civicrm/packages/DB/DataObject.php(2442): DB_common->query("INSERT INTO civicrm_uf_match (domain_id , uf_id , uf_name , contact_id ) VALU...")
#10 /var/www/menas.co/public_html/dev/wp-content/plugins/civicrm/civicrm/packages/DB/DataObject.php(1060): DB_DataObject->_query("INSERT INTO civicrm_uf_match (domain_id , uf_id , uf_name , contact_id ) VALU...")
#11 /var/www/menas.co/public_html/dev/wp-content/plugins/civicrm/civicrm/CRM/Core/DAO.php(450): DB_DataObject->insert()
#12 /var/www/menas.co/public_html/dev/wp-content/plugins/civicrm-wp-member-sync/civi-wp-ms-users.php(520): CRM_Core_DAO->save()
#13 /var/www/menas.co/public_html/dev/wp-content/plugins/civicrm-wp-member-sync/civi-wp-ms-members.php(251): Civi_WP_Member_Sync_Users->wp_create_user((Array:66))
#14 [internal function](): Civi_WP_Member_Sync_Members->membership_updated("create", "Membership", 1, Object(CRM_Member_BAO_Membership))
#15 /var/www/menas.co/public_html/dev/wp-includes/plugin.php(571): call_user_func_array((Array:2), (Array:4))
#16 /var/www/menas.co/public_html/dev/wp-content/plugins/civicrm/civicrm/CRM/Utils/Hook/WordPress.php(130): do_action_ref_array("civicrm_post", (Array:4))
#17 /var/www/menas.co/public_html/dev/wp-content/plugins/civicrm/civicrm/CRM/Utils/Hook.php(306): CRM_Utils_Hook_WordPress->invoke(4, "create", "Membership", 1, Object(CRM_Member_BAO_Membership), NULL, NULL, "civicrm_post")
#18 /var/www/menas.co/public_html/dev/wp-content/plugins/civicrm/civicrm/CRM/Member/BAO/Membership.php(180): CRM_Utils_Hook::post("create", "Membership", 1, Object(CRM_Member_BAO_Membership))
#19 /var/www/menas.co/public_html/dev/wp-content/plugins/civicrm/civicrm/CRM/Member/BAO/Membership.php(310): CRM_Member_BAO_Membership::add((Array:17), (Array:1))
#20 /var/www/menas.co/public_html/dev/wp-content/plugins/civicrm/civicrm/CRM/Member/Form/Membership.php(1593): CRM_Member_BAO_Membership::create((Array:17), (Array:1))
#21 /var/www/menas.co/public_html/dev/wp-content/plugins/civicrm/civicrm/CRM/Core/Form.php(345): CRM_Member_Form_Membership->postProcess()
#22 /var/www/menas.co/public_html/dev/wp-content/plugins/civicrm/civicrm/CRM/Core/QuickForm/Action/Upload.php(166): CRM_Core_Form->mainProcess()
#23 /var/www/menas.co/public_html/dev/wp-content/plugins/civicrm/civicrm/CRM/Core/QuickForm/Action/Upload.php(133): CRM_Core_QuickForm_Action_Upload->realPerform(Object(CRM_Member_Form_Membership), "upload")
#24 /var/www/menas.co/public_html/dev/wp-content/plugins/civicrm/civicrm/packages/HTML/QuickForm/Controller.php(203): CRM_Core_QuickForm_Action_Upload->perform(Object(CRM_Member_Form_Membership), "upload")
#25 /var/www/menas.co/public_html/dev/wp-content/plugins/civicrm/civicrm/packages/HTML/QuickForm/Page.php(103): HTML_QuickForm_Controller->handle(Object(CRM_Member_Form_Membership), "upload")
#26 /var/www/menas.co/public_html/dev/wp-content/plugins/civicrm/civicrm/CRM/Core/Controller.php(353): HTML_QuickForm_Page->handle("upload")
#27 /var/www/menas.co/public_html/dev/wp-content/plugins/civicrm/civicrm/CRM/Member/Page/Tab.php(281): CRM_Core_Controller->run()
#28 /var/www/menas.co/public_html/dev/wp-content/plugins/civicrm/civicrm/CRM/Member/Page/Tab.php(354): CRM_Member_Page_Tab->edit()
#29 /var/www/menas.co/public_html/dev/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php(312): CRM_Member_Page_Tab->run((Array:4), NULL)
#30 /var/www/menas.co/public_html/dev/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php(86): CRM_Core_Invoke::runItem((Array:14))
#31 /var/www/menas.co/public_html/dev/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php(54): CRM_Core_Invoke::_invoke((Array:4))
#32 /var/www/menas.co/public_html/dev/wp-content/plugins/civicrm/civicrm.php(1189): CRM_Core_Invoke::invoke((Array:4))
#33 [internal function](): CiviCRM_For_WordPress->invoke("")
#34 /var/www/menas.co/public_html/dev/wp-includes/plugin.php(496): call_user_func_array((Array:2), (Array:1))
#35 /var/www/menas.co/public_html/dev/wp-admin/admin.php(226): do_action("toplevel_page_CiviCRM")
#36 {main}
```

**Comment by christianwach** [comment]
@mecachisenros Thanks for the report. 

If you look at the code, no `UF_Match` entry should be created if one already exists: see:
https://github.com/christianwach/civicrm-wp-member-sync/blob/master/civi-wp-ms-users.php#L519

Can you trace what's going at that point?

**Comment by christianwach** [comment]
@mecachisenros I've added a new branch which may solve the issue. Can you re-test from the following branch?

https://github.com/christianwach/civicrm-wp-member-sync/tree/newhooks

**Comment by mecachisenros** [comment]
@christianwach I'm going to test it now, an come back with results. Thanks in advance.

**Comment by mecachisenros** [comment]
@christianwach I've made more tests in a fresh install and it seems to be working as expected now, but I noticed that if the Membership type is inherited from the Organization by relationship (ie Employer of) and I creat a new contact with the given relationship, the Member-sync wont create the Wordpress user until you edit or renew the Primary Membership owner (ie the Organisation). Instead, if I create a new contact without establishing the relationship and I add the mentioned relationship afterwards the contact was created, then the Member-sync works properly and creates a new Wordpress user.

Does that make sens?

**Comment by christianwach** [comment]
I'd assume that the entities passed to `hook_civicrm_post` must be different. My code assumes `$objectName` to be 'Membership' and `$objectRef` to be an instance of `CRM_Member_BAO_Membership`. Perhaps you can check what's being passed at that point?

Oh and if this particular issue is resolved, can you close it and open a new one please?

**Comment by christianwach** [comment]
@mecachisenros As you can see, I've merged the 'newhooks' branch to 'master' with some modifications. Thanks for the report. As I said, if you could open a new issue for inherited memberships, that'd be appreciated.

**Comment by mecachisenros** [comment]
Many thanks @christianwach, I will try to figure out playing with the CiviCRM API and I will open the issue as soon as I know something.
